### PR TITLE
Forge Update Checker

### PR DESCRIPTION
**Pull request by LotuxPunk**

### CODE REVIEW

**Comment by IronicallySub** [comment]
You pinched this from angels didn't you xD
Not that I mind, resolve the conflicts and I'll merge the PR :)

**Comment by LotuxPunk** [comment]
Absolutely, it was so well done. :D

**Comment by LotuxPunk** [comment]
Conflict resolved.
Yo be honnest, I use this also for K9 🙄

**Comment by IronicallySub** [comment]
I really don't mind xD

**Pull request merged**
