### PR TITLE
Added Worldshell for rendering outside the TARDIS

### PR DESCRIPTION
**Pull request by Snakefangox**
I've added code needed to render blocks from outside the Tardis.
I haven't actually rigged any of it up yet, because I don't know how you'd like to do it.
I hope I've made all the code clear.

### CODE REVIEW

**Comment by Spectre0987** [comment]
You are the most wonderful person I've ever met.

**Comment by Snakefangox** [comment]
Thanks! Let me know if anything doesn't make sense or doesn't work.

**Comment by ReallySub** [comment]
Do you have any example of how it could be used? It looks promising! But I have no idea where things would go....haha

**Comment by Snakefangox** [comment]
Sure, I'll add an example.

**Comment by LotuxPunk** [comment]
I don't understand what is it, but seem awesome xD

**Pull request merged**
