### PR TITLE
Snap, close/open your tardis with a finger's snap !

### PR DESCRIPTION
**Pull request by LotuxPunk**

### CODE REVIEW

**Comment by Suffril** [comment]
can you provide a streamable of this working?

**Comment by LotuxPunk** [comment]
Snap ? Snap ! https://youtu.be/hjtkBkiA47A

**Comment by Suffril** [comment]
great, it works
but perhaps add a range on it? there's no way players should be able to open the doors from 100s of blocks away

**Comment by LotuxPunk** [comment]
That's a good idea, I'll do that now

**Comment by LotuxPunk** [comment]
I'm done, son @Suffril https://streamable.com/o6fod

**Pull request merged**
