### PR TITLE
Command : Teleport to your TARDIS

### PR DESCRIPTION
**Pull request by LotuxPunk**

### CODE REVIEW

**Comment by SandedShoes** [comment]
I would suggest putting these behind some kind of config or gamerule, some people may use this as a cop out of doing things

**Comment by LotuxPunk** [comment]
Absolutely, I'll work on it

**Comment by LotuxPunk** [comment]
Is that okay now ?

**Comment by SandedShoes** [comment]
Looks it yeah, just need @Spectre0987's approval now

**Comment by LotuxPunk** [comment]
If it's okay, I'll do the others.

**Comment by SandedShoes** [comment]
@LotuxPunk Resolve conflicts when you get the chance :)

**Comment by LotuxPunk** [comment]
There was no conflict at first :o 

Solved btw

**Comment by SandedShoes** [comment]
<3

**Pull request merged**
