### PR TITLE
Hads , Not taking off when broken or in flight

### PR DESCRIPTION
**Pull request by Josia50**
Hads won't take-off when a circuit is broken , (More realistic). It will also disable hads afterwards. also a check for when it's in flight (Preventing problems)

### CODE REVIEW

**Comment by Suffril** [comment]
What?

**Comment by Josia50** [comment]
it's more a enhancement of realisticness

**Comment by Suffril** [comment]
It's more I don't understand what it is you're doing

**Comment by Josia50** [comment]
Circuit breaks that is required to fly => Someone shoots tardis on exterior when hads is enabled => Tardis will disable hads and will play cloister and engine stutter.

**Comment by Josia50** [comment]
And when it's inflight (if they shoot on a dematerialising exterior) it won't give problems as it used to freeze me when i tried with some repeating sounds...

**Pull request closed without merging**
